# render.yaml (Final Correct Version)

services:
  # A Worker for our long-running Python bot
  - type: worker
    name: telegram-home-bot
    env: python
    # How to install dependencies
    buildCommand: "pip install -r requirements.txt"
    # The command to start the bot
    startCommand: "python nice.py"
    # The disk is defined directly inside the service that uses it.
    # The key is 'disk' (singular).
    disk:
      name: bot-database-disk # A name for the disk
      mountPath: /var/data     # The location to make it available
      sizeGB: 1                # 1 GB is more than enough
