# render.yaml (Corrected Version)

# First, define the disks that will be available.
# This is a top-level section.
disks:
  - name: bot-database-disk   # A name for the disk
    mountPath: /var/data       # The location it will be mounted
    sizeGB: 1                  # 1 GB is plenty for a JSON file

# Second, define the services that will run.
services:
  - type: worker
    name: telegram-home-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python nice.py"
    # Now, link this service to the disk defined above.
    # Note: this is 'disk' (singular), not 'disks'.
    disk:
      name: bot-database-disk  # Must match the name above
      mountPath: /var/data     # Must match the mountPath above
